name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: run
      run: |
        npm ci
        npm run mirror
        sed -i 's/  PUBLIC\./  PUBLIC.\n\n  INTERFACES if_serializable_object./' src/z2ui5_if_ajson_mapping.intf.abap
        git status
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: auto-update
        title: "Automatic Update"
        commit-message: "Automated changes"
        body: "This PR contains automated changes."
        labels: "auto-merge"
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-created == 'true'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash
